export const webProjectsBase = {
	aeducational: {
		label: 'aEducational',
		tagLine: 'Free English writing resources.',
		desc1: 'Free English writing resources.',
		desc2: 'Get letters, essays, notices, speeches, debates, and paragraphs - all written by me. Perfect for students and learners.',
		href: 'https://education.arshsaxena.in/',
		icon: '/made-by-arsh/web-projects/icons/aeducational-app-icon.webp',
		img: '/made-by-arsh/web-projects/imgs/aeducational-desktop.webp',
	},
	aconverter: {
		label: 'aConverter',
		tagLine: 'Convert in multiple units.',
		desc1: 'Convert units instantly, for free.',
		desc2: 'Easily switch between units of length, mass, temperature, and speed. More categories coming soon!',
		href: 'https://converter.arshsaxena.in/',
		icon: '/made-by-arsh/web-projects/icons/aconverter-app-icon.webp',
		img: '/made-by-arsh/web-projects/imgs/aconverter-desktop.webp',
	},
	solarsystem: {
		label: 'Solar System',
		tagLine: 'HTML, CSS, and JavaScript.',
		desc1: 'Built with HTML, CSS, and JavaScript - watch years fly by in seconds. ',
		desc2: 'Yes, even Pluto is here.',
		href: 'https://solarsystem.arshsaxena.in/',
		icon: '/made-by-arsh/web-projects/icons/solarsystem-icon.webp',
		img: '/made-by-arsh/web-projects/imgs/solarsystem.webp',
	},
	colors: {
		label: 'Colors',
		tagLine: 'Hex. RGB. RGBA.',
		desc1: 'Random color generator. Simple. Fast. Free.',
		desc2: 'Get HEX, RGB, and RGBA values in a click. Also supports custom input.',
		href: 'https://colors.arshsaxena.in/',
		icon: '/made-by-arsh/web-projects/icons/colors-icon.webp',
		img: '/made-by-arsh/web-projects/imgs/colors-desktop.webp',
	},
	qr: {
		label: 'QR Code Generator',
		tagLine: 'Type. Generate. QR.',
		desc1: 'Free and simple online QR code generator.',
		desc2: 'Convert text, websites, phone numbers, emails, and more into QR codes. Download and share like any image.',
		href: 'https://qr.arshsaxena.in/',
		icon: '/made-by-arsh/web-projects/icons/qr-icon.webp',
		img: '/made-by-arsh/web-projects/imgs/qr-desktop.webp',
	},
	weather: {
		label: 'Weather',
		tagLine: 'Weather, worldwide.',
		desc1: 'Live weather data, worldwide.',
		desc2: 'Check current temperature, feels-like, highs, lows, pressure, humidity, wind, clouds, and more - for any location.',
		href: 'https://weather.arshsaxena.in/',
		icon: '/made-by-arsh/web-projects/icons/weather-icon.webp',
		img: '/made-by-arsh/web-projects/imgs/weather-desktop.webp',
	},
};
